name: Deploy Laravel official website

on:
  push:
    branches: [master]

jobs:
  create-deployment-artifacts:
    name: create deployment artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: compile source code
        run:
          npm install
          npm run prod
  
    
